
POST https://mellw.hasura.app/v1alpha1/pg_dump
Content-Type: application/json
X-Hasura-Role: admin
x-hasura-admin-secret: rKpA@W3S2PlZsK

{
  "opts": ["-O","--schema", "public"],
  "clean_output": true
}

// heroku pg:backups:capture --app fierce-springs-92752
// heroku pg:backups:download --app fierce-springs-92752
// ssh -i "~/Downloads/awskp-brtiro1002.pem" ubuntu@ec2-18-116-231-109.us-east-2.compute.amazonaws.com